import Dua from '../models/Dua.js';

const duas = [
  // === MORNING (5) ===
  {
    category: 'morning',
    title: { en: 'Morning Dua 1', ur: 'صبح کی دعا ۱' },
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ',
    urdu: 'اے اللہ! ہم نے تیرے نام پر صبح کی اور تیرے نام پر شام کی، تیرے نام پر جیتے ہیں اور تیرے نام پر مرتے ہیں اور تیری طرف پلٹنا ہے۔',
    english: 'O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.',
    transliteration: 'Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilaykan nushoor',
    reference: 'Sunan Abi Dawud 5068',
  },
  {
    category: 'morning',
    title: { en: 'Morning Dua 2', ur: 'صبح کی دعا ۲' },
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ',
    urdu: 'اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں، تو نے مجھے پیدا کیا اور میں تیرا بندہ ہوں۔',
    english: 'O Allah, You are my Lord, none has the right to be worshipped but You, You created me and I am Your servant.',
    transliteration: 'Allahumma anta rabbi la ilaha illa anta khalaqtani wa ana abduka',
    reference: 'Sahih Bukhari 6306',
  },
  {
    category: 'morning',
    title: { en: 'Morning Dua 3', ur: 'صبح کی دعا ۳' },
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
    urdu: 'میں اللہ کو رب، اسلام کو دین اور محمد صلی اللہ علیہ وسلم کو نبی مان کر راضی ہوں۔',
    english: 'I am pleased with Allah as my Lord, Islam as my religion, and Muhammad (peace be upon him) as my Prophet.',
    transliteration: 'Radeetu billahi rabban wa bil islami deenan wa bi Muhammadin sallallahu alayhi wa sallama nabiyya',
    reference: 'Sunan Abi Dawud 5072',
  },
  {
    category: 'morning',
    title: { en: 'Morning Dua 4', ur: 'صبح کی دعا ۴' },
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ',
    urdu: 'اللہ پاک ہے اور اس کی حمد ہے، جتنی مخلوق ہے، جتنی اس کی رضا ہے، جتنا عرش کا وزن ہے اور جتنے اس کے کلمات ہیں۔',
    english: 'Glory and praise be to Allah, as many times as the number of His creatures, in accordance with His good pleasure, equal to the weight of His Throne and equal to the ink of His words.',
    transliteration: 'Subhanallahi wa bihamdihi adada khalqihi wa rida nafsihi wa zinata arshihi wa midada kalimatihi',
    reference: 'Sahih Muslim 2726',
  },
  {
    category: 'morning',
    title: { en: 'Morning Dua 5', ur: 'صبح کی دعا ۵' },
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا',
    urdu: 'اے اللہ! میں تجھ سے نفع بخش علم، پاکیزہ رزق اور قبول شدہ عمل مانگتا ہوں۔',
    english: 'O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.',
    transliteration: 'Allahumma inni as\'aluka ilman nafi\'an wa rizqan tayyiban wa amalan mutaqabbalan',
    reference: 'Sunan Ibn Majah 925',
  },
  // === EVENING (5) ===
  {
    category: 'evening',
    title: { en: 'Evening Dua 1', ur: 'شام کی دعا ۱' },
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ',
    urdu: 'اے اللہ! ہم نے تیرے نام پر شام کی اور تیرے نام پر صبح کی، تیرے نام پر جیتے ہیں اور تیرے نام پر مرتے ہیں اور تیری طرف لوٹنا ہے۔',
    english: 'O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the final return.',
    transliteration: 'Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilaykal masir',
    reference: 'Sunan Abi Dawud 5068',
  },
  {
    category: 'evening',
    title: { en: 'Evening Dua 2', ur: 'شام کی دعا ۲' },
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    urdu: 'ہم نے شام کی اور سارا ملک اللہ ہی کا ہے، تمام تعریفیں اللہ کے لیے ہیں، اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے اس کا کوئی شریک نہیں۔',
    english: 'We have reached the evening and at this very time all sovereignty belongs to Allah, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.',
    transliteration: 'Amsayna wa amsal mulku lillahi walhamdu lillahi la ilaha illallahu wahdahu la sharika lah',
    reference: 'Sahih Muslim 2723',
  },
  {
    category: 'evening',
    title: { en: 'Evening Dua 3', ur: 'شام کی دعا ۳' },
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا فِيهَا وَأَعُوذُ بِكَ مِنْ شَرِّ هَذِهِ اللَّيْلَةِ وَشَرِّ مَا فِيهَا',
    urdu: 'اے اللہ! میں تجھ سے اس رات کی بھلائی اور اس میں جو کچھ ہے اس کی بھلائی مانگتا ہوں اور اس رات کے شر اور اس میں جو کچھ ہے اس کے شر سے تیری پناہ چاہتا ہوں۔',
    english: 'O Allah, I ask You for the good of this night and the good of what is in it, and I seek refuge in You from the evil of this night and the evil of what is in it.',
    transliteration: 'Allahumma inni as\'aluka khayra hadhihil laylati wa khayra ma fiha wa a\'udhu bika min sharri hadhihil laylati wa sharri ma fiha',
    reference: 'Sunan Abi Dawud 5067',
  },
  {
    category: 'evening',
    title: { en: 'Evening Dua 4', ur: 'شام کی دعا ۴' },
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    urdu: 'اللہ کے نام کے ساتھ جس کے نام سے زمین اور آسمان میں کوئی چیز نقصان نہیں پہنچا سکتی اور وہ سننے والا جاننے والا ہے۔',
    english: 'In the name of Allah with whose name nothing can cause harm on earth nor in the heavens, and He is the All-Hearing, All-Knowing.',
    transliteration: 'Bismillahil lazi la yadurru ma\'asmihi shay\'un fil ardi wa la fis samai wa huwas sami\'ul alim',
    reference: 'Sunan Abi Dawud 5088',
  },
  {
    category: 'evening',
    title: { en: 'Evening Dua 5', ur: 'شام کی دعا ۵' },
    arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي لَا إِلَهَ إِلَّا أَنْتَ',
    urdu: 'اے اللہ! میرے جسم کو عافیت دے، میرے کان کو عافیت دے، میری آنکھ کو عافیت دے، تیرے سوا کوئی معبود نہیں۔',
    english: 'O Allah, grant my body health, O Allah, grant my hearing health, O Allah, grant my sight health, none has the right to be worshipped except You.',
    transliteration: 'Allahumma afini fi badani Allahumma afini fi sam\'i Allahumma afini fi basari la ilaha illa anta',
    reference: 'Sunan Abi Dawud 5090',
  },
  // === SLEEP (3) ===
  {
    category: 'sleep',
    title: { en: 'Sleep Dua 1', ur: 'سونے کی دعا ۱' },
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    urdu: 'اے اللہ! تیرے نام کے ساتھ میں مرتا ہوں اور جیتا ہوں۔',
    english: 'In Your name, O Allah, I die and I live.',
    transliteration: 'Bismikallahumma amutu wa ahya',
    reference: 'Sahih Bukhari 6312',
  },
  {
    category: 'sleep',
    title: { en: 'Sleep Dua 2', ur: 'سونے کی دعا ۲' },
    arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
    urdu: 'اے اللہ! مجھے اپنے عذاب سے بچا لے جس دن تو اپنے بندوں کو اٹھائے گا۔',
    english: 'O Allah, protect me from Your punishment on the Day You resurrect Your servants.',
    transliteration: 'Allahumma qini azabaka yama tab\'athu ibadak',
    reference: 'Sunan Abi Dawud 5045',
  },
  {
    category: 'sleep',
    title: { en: 'Sleep Dua 3', ur: 'سونے کی دعا ۳' },
    arabic: 'سُبْحَانَ اللَّهِ (۳۳) ، وَالْحَمْدُ لِلَّهِ (۳۳) ، وَاللَّهُ أَكْبَرُ (۳۴)',
    urdu: 'اللہ پاک ہے (۳۳ بار)، اللہ کی تعریف ہے (۳۳ بار)، اللہ سب سے بڑا ہے (۳۴ بار)',
    english: 'Glory to Allah (33 times), Praise to Allah (33 times), Allah is the Greatest (34 times).',
    transliteration: 'Subhanallah (33x), Alhamdulillah (33x), Allahu Akbar (34x)',
    reference: 'Sahih Bukhari 6318',
  },
  // === FOOD (3) ===
  {
    category: 'food',
    title: { en: 'Before Eating', ur: 'کھانے سے پہلے' },
    arabic: 'بِسْمِ اللَّهِ',
    urdu: 'اللہ کے نام سے',
    english: 'In the name of Allah.',
    transliteration: 'Bismillah',
    reference: 'Sahih Bukhari 5376',
  },
  {
    category: 'food',
    title: { en: 'After Eating', ur: 'کھانے کے بعد' },
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    urdu: 'اللہ کا شکر ہے جس نے مجھے یہ کھلایا اور رزق دیا، میرے کسی زور اور طاقت کے بغیر۔',
    english: 'All praise is due to Allah Who fed me this and provided it to me without any might or power from myself.',
    transliteration: 'Alhamdu lillahil lazi at\'amani haza wa razaqanihi min ghayri hawlin minni wa la quwwah',
    reference: 'Sunan Abi Dawud 4023',
  },
  {
    category: 'food',
    title: { en: 'When Invited to Eat', ur: 'دعوت پر کھاتے وقت' },
    arabic: 'اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ',
    urdu: 'اے اللہ! ان کے لیے اس رزق میں برکت دے جو تو نے انہیں دیا، انہیں بخش دے اور ان پر رحم فرما۔',
    english: 'O Allah, bless them in what You have provided for them, forgive them and have mercy on them.',
    transliteration: 'Allahumma barik lahum fima razaqtahum waghfir lahum warhamhum',
    reference: 'Sahih Muslim 2042',
  },
  // === TRAVEL (3) ===
  {
    category: 'travel',
    title: { en: 'Before Travel', ur: 'سفر سے پہلے' },
    arabic: 'اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ',
    urdu: 'اللہ سب سے بڑا ہے، پاک ہے وہ جس نے اسے ہمارے لیے مسخر کیا اور ہم اسے قابو کرنے والے نہ تھے اور ہم اپنے رب کی طرف لوٹنے والے ہیں۔',
    english: 'Allah is the Greatest, Allah is the Greatest, Allah is the Greatest. Glory is to Him Who has subjected this to us, and we could not have it otherwise. And indeed, to our Lord we will return.',
    transliteration: 'Allahu Akbar Allahu Akbar Allahu Akbar, Subhanallazi sakhkhara lana haza wa ma kunna lahu muqrinin wa inna ila rabbina lamunqalibun',
    reference: 'Surah Az-Zukhruf 43:13-14',
  },
  {
    category: 'travel',
    title: { en: 'Travel Dua', ur: 'سفر کی دعا' },
    arabic: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَىٰ وَمِنَ الْعَمَلِ مَا تَرْضَىٰ',
    urdu: 'اے اللہ! ہم تجھ سے اس سفر میں نیکی اور پرہیزگاری اور ایسے عمل کا سوال کرتے ہیں جو تو پسند کرے۔',
    english: 'O Allah, we ask You for righteousness and piety in this journey of ours, and for deeds that please You.',
    transliteration: 'Allahumma inna nasaluka fi safarina hadhil birra wat taqwa wa minal amali ma tarda',
    reference: 'Sahih Muslim 1342',
  },
  {
    category: 'travel',
    title: { en: 'Return from Travel', ur: 'سفر سے واپسی' },
    arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
    urdu: 'ہم لوٹنے والے ہیں، توبہ کرنے والے ہیں، عبادت کرنے والے ہیں، اپنے رب کی تعریف کرنے والے ہیں۔',
    english: 'We return, repentant, worshipping, and praising our Lord.',
    transliteration: 'Aayibuna taibuna abiduna lirabbina hamidun',
    reference: 'Sahih Bukhari 3085',
  },
  // === HARDSHIP (5) ===
  {
    category: 'hardship',
    title: { en: 'Dua for Distress', ur: 'پریشانی کی دعا' },
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ',
    urdu: 'اللہ کے سوا کوئی معبود نہیں جو عظیم اور بردبار ہے، عرش عظیم کا رب، آسمانوں اور زمین کا رب اور عرش کریم کا رب۔',
    english: 'None has the right to be worshipped except Allah, the Mighty, the Forbearing. None has the right to be worshipped except Allah, Lord of the Mighty Throne.',
    transliteration: 'La ilaha illallahu azimul halim, la ilaha illallahu Rabbul arshil azim, la ilaha illallahu Rabbus samawati wa Rabbul ardi wa Rabbul arshil karim',
    reference: 'Sahih Bukhari 6346',
  },
  {
    category: 'hardship',
    title: { en: 'Dua for Anxiety', ur: 'بے چینی کی دعا' },
    arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ ابْنُ عَبْدِكَ ابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ مَاضٍ فِيَّ حُكْمُكَ عَدْلٌ فِيَّ قَضَاؤُكَ',
    urdu: 'اے اللہ! میں تیرا بندہ ہوں، تیرے بندے کا بیٹا، تیری بندی کا بیٹا، میری پیشانی تیرے ہاتھ ہے، تیرا حکم مجھ پر نافذ ہے، تیرا فیصلہ میرے بارے میں عین انصاف ہے۔',
    english: 'O Allah, I am Your servant, son of Your servant, son of Your maidservant. My forelock is in Your hand, Your command over me is forever executed and Your decree over me is just.',
    transliteration: 'Allahumma inni abduka, ibnu abdika, ibnu amatika, nasiyati bi yadik, maadin fiyya hukmuk, adlun fiyya qadaauk',
    reference: 'Musnad Ahmad 3712',
  },
  {
    category: 'hardship',
    title: { en: 'Dua When in Difficulty', ur: 'مشکل وقت کی دعا' },
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    urdu: 'میرے لیے اللہ کافی ہے، اس کے سوا کوئی معبود نہیں، اسی پر میں نے بھروسہ کیا اور وہ عرش عظیم کا رب ہے۔',
    english: 'Sufficient for me is Allah, none has the right to be worshipped except Him, upon Him I rely and He is the Lord of the Mighty Throne.',
    transliteration: 'Hasbiyallahu la ilaha illa huwa alayhi tawakkaltu wa huwa Rabbul arshil azim',
    reference: 'Surah At-Tawbah 9:129',
  },
  {
    category: 'hardship',
    title: { en: 'Dua for Relief', ur: 'فرج کی دعا' },
    arabic: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    urdu: 'تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ظالموں میں سے تھا۔',
    english: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoing.',
    transliteration: 'La ilaha illa anta subhanaka inni kuntu minaz zalimin',
    reference: 'Surah Al-Anbiya 21:87',
  },
  {
    category: 'hardship',
    title: { en: 'Dua for Sorrow', ur: 'غم کی دعا' },
    arabic: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ وَأَصْلِحْ لِي شَأْنِي كُلَّهُ لَا إِلَهَ إِلَّا أَنْتَ',
    urdu: 'اے اللہ! میں تیری رحمت کا امیدوار ہوں، مجھے پلک جھپکنے کے لیے بھی میرے نفس کے سپرد نہ کر اور میرے تمام کام درست فرما، تیرے سوا کوئی معبود نہیں۔',
    english: 'O Allah, I hope for Your mercy, so do not entrust me to myself for the blink of an eye, and set right all my affairs. None has the right to be worshipped except You.',
    transliteration: 'Allahumma rahmataka arju fala takilni ila nafsi tarfata aynin wa aslih li shani kullahu la ilaha illa anta',
    reference: 'Sunan Abi Dawud 5090',
  },
  // === FORGIVENESS (5) ===
  {
    category: 'forgiveness',
    title: { en: 'Sayyidul Istighfar', ur: 'سید الاستغفار' },
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    urdu: 'اے اللہ! تو میرا رب ہے، تیرے سوا کوئی معبود نہیں، میں تیرے عہد اور وعدے پر ہوں جتنا میں کر سکتا ہوں۔',
    english: 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant. I abide by Your covenant and promise as best I can.',
    transliteration: 'Allahumma anta rabbi la ilaha illa anta khalaqtani wa ana abduka wa ana ala ahdika wa wa\'dika mastata\'tu',
    reference: 'Sahih Bukhari 6306',
  },
  {
    category: 'forgiveness',
    title: { en: 'Dua for Forgiveness', ur: 'مغفرت کی دعا' },
    arabic: 'رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ',
    urdu: 'اے ہمارے رب! ہم ایمان لائے، پس ہمارے گناہ معاف فرما اور ہمیں جہنم کے عذاب سے بچا۔',
    english: 'Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.',
    transliteration: 'Rabbana innana amanna faghfir lana dhunubana wa qina azaban naar',
    reference: 'Surah Aal-e-Imran 3:16',
  },
  {
    category: 'forgiveness',
    title: { en: 'Istighfar', ur: 'استغفار' },
    arabic: 'أَسْتَغْفِرُ اللَّهَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ',
    urdu: 'میں اللہ سے مغفرت مانگتا ہوں جس کے سوا کوئی معبود نہیں، وہ زندہ اور قائم رکھنے والا ہے اور میں اس کی طرف توبہ کرتا ہوں۔',
    english: 'I seek forgiveness from Allah, the One besides whom none has the right to be worshipped, the Ever-Living, the Self-Sustaining, and I repent to Him.',
    transliteration: 'Astaghfirullaha allazi la ilaha illa huwal hayyul qayyuma wa atubu ilayh',
    reference: 'Sunan Abi Dawud 1517',
  },
  {
    category: 'forgiveness',
    title: { en: 'Dua for Mercy', ur: 'رحمت کی دعا' },
    arabic: 'رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِنْ قَبْلِنَا',
    urdu: 'اے ہمارے رب! اگر ہم بھول جائیں یا غلطی کریں تو ہماری گرفت نہ فرما۔',
    english: 'Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us.',
    transliteration: 'Rabbana la tuakhidhna in naseena aw akhtana rabbana wa la tahmil alayna isran kama hamaltahu alal lazina min qablina',
    reference: 'Surah Al-Baqarah 2:286',
  },
  {
    category: 'forgiveness',
    title: { en: 'Dua for Pardon', ur: 'درگزر کی دعا' },
    arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
    urdu: 'اے اللہ! تو معاف کرنے والا ہے، معاف کرنا پسند کرتا ہے، مجھے معاف فرما۔',
    english: 'O Allah, You are Pardoning and love pardon, so pardon me.',
    transliteration: 'Allahumma innaka afuwwun tuhibbul afwa fa\'fu anni',
    reference: 'Sunan Ibn Majah 3850',
  },
  // === PROTECTION (5) ===
  {
    category: 'protection',
    title: { en: 'Ayat al-Kursi', ur: 'آیت الکرسی' },
    arabic: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
    urdu: 'اللہ کے سوا کوئی معبود نہیں، وہ زندہ اور سب کا سنبھالنے والا ہے، اسے نہ اونگھ آتی ہے نہ نیند۔',
    english: 'Allah - there is no deity except Him, the Ever-Living, the Self-Sustaining. Neither drowsiness overtakes Him nor sleep.',
    transliteration: 'Allahu la ilaha illa huwal hayyul qayyum, la ta\'khudhuhu sinatun wa la nawm',
    reference: 'Surah Al-Baqarah 2:255',
  },
  {
    category: 'protection',
    title: { en: 'Protection Dua', ur: 'حفاظت کی دعا' },
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    urdu: 'اللہ کے نام کے ساتھ جس کے نام سے زمین اور آسمان میں کوئی چیز نقصان نہیں پہنچا سکتی۔',
    english: 'In the name of Allah with whose name nothing can cause harm on earth nor in the heavens, and He is the All-Hearing, All-Knowing.',
    transliteration: 'Bismillahil lazi la yadurru ma\'asmihi shay\'un fil ardi wa la fis samai wa huwas sami\'ul alim',
    reference: 'Sunan Abi Dawud 5088',
  },
  {
    category: 'protection',
    title: { en: 'Morning and Evening Protection', ur: 'صبح شام کی حفاظت' },
    arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي لَا إِلَهَ إِلَّا أَنْتَ',
    urdu: 'اے اللہ! میرے جسم کو عافیت دے، میرے کان کو عافیت دے، میری آنکھ کو عافیت دے۔',
    english: 'O Allah, grant my body health, O Allah, grant my hearing health, O Allah, grant my sight health.',
    transliteration: 'Allahumma afini fi badani Allahumma afini fi sam\'i Allahumma afini fi basari',
    reference: 'Sunan Abi Dawud 5090',
  },
  {
    category: 'protection',
    title: { en: 'Protection from Evil', ur: 'برائی سے حفاظت' },
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    urdu: 'میں اللہ کے کامل کلمات کی پناہ میں آتا ہوں اس کی مخلوق کے شر سے۔',
    english: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    transliteration: 'A\'udhu bi kalimatillahit tammati min sharri ma khalaq',
    reference: 'Sahih Muslim 2709',
  },
  {
    category: 'protection',
    title: { en: 'Protection from Shaytan', ur: 'شیطان سے حفاظت' },
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    urdu: 'میں اللہ کی پناہ میں آتا ہوں شیطان مردود سے۔',
    english: 'I seek refuge with Allah from the accursed Shaytan.',
    transliteration: 'A\'udhu billahi minash shaytanir rajim',
    reference: 'Surah An-Nahl 16:98',
  },
  // === RAMADAN (10) ===
  {
    category: 'ramadan',
    title: { en: 'Dua for Suhoor', ur: 'سحری کی دعا' },
    arabic: 'وَبِصَوْمِ غَدٍ نَّوَيْتُ مِنْ شَهْرِ رَمَضَانَ',
    urdu: 'میں نے ماہ رمضان کے کل کے روزے کی نیت کی۔',
    english: 'I intend to fast tomorrow in the month of Ramadan.',
    transliteration: 'Wa bi sawmi ghadin nawatu min shahri ramadan',
    reference: 'Fiqh',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Iftar', ur: 'افطار کی دعا' },
    arabic: 'اللَّهُمَّ لَكَ صُمْتُ وَعَلَىٰ رِزْقِكَ أَفْطَرْتُ',
    urdu: 'اے اللہ! میں نے تیرے لیے روزہ رکھا اور تیرے رزق سے افطار کیا۔',
    english: 'O Allah, I have fasted for You and with Your provision I break my fast.',
    transliteration: 'Allahumma laka sumtu wa ala rizqika aftartu',
    reference: 'Sunan Abi Dawud 2358',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua at Iftar', ur: 'افطار کے وقت دعا' },
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
    urdu: 'پیاس ختم ہو گئی، رگیں تر ہو گئیں اور ثابت ہو گیا اجر ان شاء اللہ۔',
    english: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    transliteration: 'Dhahabaz zama wabtallatil urooqu wa thabatal ajru inshaAllah',
    reference: 'Sunan Abi Dawud 2357',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Laylatul Qadr', ur: 'شب قدر کی دعا' },
    arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
    urdu: 'اے اللہ! تو معاف کرنے والا ہے، معاف کرنا پسند کرتا ہے، مجھے معاف فرما۔',
    english: 'O Allah, You are Pardoning and love pardon, so pardon me.',
    transliteration: 'Allahumma innaka afuwwun tuhibbul afwa fa\'fu anni',
    reference: 'Sunan Ibn Majah 3850',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Taraweeh', ur: 'تراویح کی دعا' },
    arabic: 'سُبْحَانَ ذِي الْمُلْكِ وَالْمَلَكُوتِ سُبْحَانَ ذِي الْعِزَّةِ وَالْعَظَمَةِ وَالْقُدْرَةِ وَالْكِبْرِيَاءِ وَالْجَبَرُوتِ',
    urdu: 'پاک ہے بادشاہی اور عظمت والا، پاک ہے عزت، عظمت، قدرت اور کبریائی والا۔',
    english: 'Glory to the Possessor of the Kingdom and the Dominion, Glory to the Possessor of Might, Majesty, Power, Grandeur and Supremacy.',
    transliteration: 'Subhana dhil mulki wal malakuti subhana dhil izzati wal azamati wal qudrati wal kibriyai wal jabrut',
    reference: 'Taraweeh practice',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Qiyam', ur: 'قیام کی دعا' },
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    urdu: 'اے ہمارے رب! ہمیں دنیا میں بھلائی اور آخرت میں بھلائی دے اور ہمیں جہنم کے عذاب سے بچا۔',
    english: 'Our Lord, give us in this world good and in the Hereafter good and protect us from the punishment of the Fire.',
    transliteration: 'Rabbana atina fid dunya hasanah wa fil aakhirati hasanah wa qina azaban naar',
    reference: 'Surah Al-Baqarah 2:201',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Strength in Ramadan', ur: 'رمضان میں طاقت کی دعا' },
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَىٰ صِيَامِهِ وَقِيَامِهِ',
    urdu: 'اے اللہ! میرے روزے اور قیام میں میری مدد فرما۔',
    english: 'O Allah, help me to fast and to stand in prayer during Ramadan.',
    transliteration: 'Allahumma a\'inni ala siyamihi wa qiyamihi',
    reference: 'Fiqh',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Acceptance', ur: 'قبولیت کی دعا' },
    arabic: 'اللَّهُمَّ تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ',
    urdu: 'اے اللہ! ہم سے قبول فرما، بے شک تو سننے والا جاننے والا ہے۔',
    english: 'O Allah, accept from us. Indeed, You are the All-Hearing, the All-Knowing.',
    transliteration: 'Allahumma taqabbal minna innaka antas sami\'ul alim',
    reference: 'Surah Al-Baqarah 2:127',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Itikaf', ur: 'اعتکاف کی دعا' },
    arabic: 'اللَّهُمَّ اجْعَلْنَا مِنَ الْمُعْتَكِفِينَ الْمُقْتَدِينَ بِسُنَّةِ نَبِيِّكَ',
    urdu: 'اے اللہ! ہمیں اعتکاف کرنے والوں میں سے بنا جو تیرے نبی کی سنت پر چلتے ہیں۔',
    english: 'O Allah, make us among those who observe Itikaf following the Sunnah of Your Prophet.',
    transliteration: 'Allahummaj\'alna minal mutakifeen al muqtadeena bi sunnati nabiyyika',
    reference: 'Fiqh',
  },
  {
    category: 'ramadan',
    title: { en: 'Dua for Eid', ur: 'عید کی دعا' },
    arabic: 'اللَّهُمَّ اجْعَلْهُ عِيدًا مُبَارَكًا لَنَا وَتَقَبَّلْ فِيهِ أَعْمَالَنَا',
    urdu: 'اے اللہ! اسے ہمارے لیے مبارک عید بنا اور اس میں ہمارے اعمال قبول فرما۔',
    english: 'O Allah, make this a blessed Eid for us and accept our deeds during it.',
    transliteration: 'Allahummaj\'alhu eedan mubarakan lana wa taqabbal fihi a\'malana',
    reference: 'Fiqh',
  },
];

const seedDuas = async () => {
  try {
    await Dua.deleteMany({});
    await Dua.insertMany(duas);
    console.log(`${duas.length} Duas seeded successfully`);
  } catch (error) {
    console.error('Error seeding duas:', error.message);
    throw error;
  }
};

export default seedDuas;
