/// Asma-ul-Husna — used by LoadingList to turn wait time into dhikr:
/// while any streak screen loads, a different name of Allah is shown
/// every second (randomized start, then walking the list).
class AllahName {
  final String ar;
  final String tr;
  final String en;
  final String ur;

  const AllahName(this.ar, this.tr, this.en, this.ur);
}

const List<AllahName> allahNames = [
  AllahName('الرَّحْمَنُ', 'Ar-Rahman', 'The Most Compassionate', 'نہایت مہربان'),
  AllahName('الرَّحِيمُ', 'Ar-Raheem', 'The Most Merciful', 'بہت رحم فرمانے والا'),
  AllahName('الْمَلِكُ', 'Al-Malik', 'The King', 'بادشاہ'),
  AllahName('الْقُدُّوسُ', 'Al-Quddus', 'The Most Holy', 'پاک ذات'),
  AllahName('السَّلَامُ', 'As-Salam', 'The Source of Peace', 'سلامتی دینے والا'),
  AllahName('الْمُؤْمِنُ', 'Al-Mumin', 'The Giver of Faith', 'ایمان دینے والا'),
  AllahName('الْمُهَيْمِنُ', 'Al-Muhaymin', 'The Guardian', 'حفاظت کرنے والا'),
  AllahName('الْعَزِيزُ', 'Al-Aziz', 'The Almighty', 'غالب'),
  AllahName('الْجَبَّارُ', 'Al-Jabbar', 'The Majestic', 'بزرگی والا'),
  AllahName('الْمُتَكَبِّرُ', 'Al-Mutakabbir', 'The Supreme', 'سب سے برتر'),
  AllahName('الْخَالِقُ', 'Al-Khaliq', 'The Creator', 'پیدا کرنے والا'),
  AllahName('الْبَارِئُ', 'Al-Bari', 'The Originator', 'بنانے والا'),
  AllahName('الْمُصَوِّرُ', 'Al-Musawwir', 'The Fashioner', 'صورتیں بنانے والا'),
  AllahName('الْغَفَّارُ', 'Al-Ghaffar', 'The All-Forgiving', 'بہت بخشنے والا'),
  AllahName('الْقَهَّارُ', 'Al-Qahhar', 'The Dominator', 'سب پر غالب'),
  AllahName('الْوَهَّابُ', 'Al-Wahhab', 'The Bestower', 'بے حساب عطا کرنے والا'),
  AllahName('الرَّزَّاقُ', 'Ar-Razzaq', 'The Provider', 'رزق دینے والا'),
  AllahName('الْفَتَّاحُ', 'Al-Fattah', 'The Opener', 'فتح دینے والا'),
  AllahName('الْعَلِيمُ', 'Al-Alim', 'The All-Knowing', 'سب کچھ جاننے والا'),
  AllahName('الْقَابِضُ', 'Al-Qabid', 'The Withholder', 'روکنے والا'),
  AllahName('الْبَاسِطُ', 'Al-Basit', 'The Expander', 'وسعت دینے والا'),
  AllahName('الْخَافِضُ', 'Al-Khafid', 'The Abaser', 'پست کرنے والا'),
  AllahName('الرَّافِعُ', 'Ar-Rafi', 'The Exalter', 'بلند کرنے والا'),
  AllahName('الْمُعِزُّ', 'Al-Muizz', 'The Honourer', 'عزت دینے والا'),
  AllahName('الْمُذِلُّ', 'Al-Muzil', 'The Dishonourer', 'ذلت دینے والا'),
  AllahName('السَّمِيعُ', 'As-Sami', 'The All-Hearing', 'سب کچھ سنتا ہوا'),
  AllahName('الْبَصِيرُ', 'Al-Basir', 'The All-Seeing', 'سب کچھ دیکھتا ہوا'),
  AllahName('الْحَكَمُ', 'Al-Hakam', 'The Judge', 'فیصلہ کرنے والا'),
  AllahName('الْعَدْلُ', 'Al-Adl', 'The Just', 'انصاف والا'),
  AllahName('اللَّطِيفُ', 'Al-Latif', 'The Subtle', 'لطف کرنے والا'),
  AllahName('الْخَبِيرُ', 'Al-Khabir', 'The All-Aware', 'باخبر'),
  AllahName('الْحَلِيمُ', 'Al-Halim', 'The Forbearing', 'برداشت والا'),
  AllahName('الْعَظِيمُ', 'Al-Azim', 'The Magnificent', 'عظمت والا'),
  AllahName('الْغَفُورُ', 'Al-Ghafoor', 'The Forgiving', 'بخشنے والا'),
  AllahName('الشَّكُورُ', 'Ash-Shakur', 'The Appreciative', 'قدردانی کرنے والا'),
  AllahName('الْعَلِيُّ', 'Al-Ali', 'The Most High', 'سب سے بلند'),
  AllahName('الْكَبِيرُ', 'Al-Kabir', 'The Greatest', 'سب سے بڑا'),
  AllahName('الْحَفِيظُ', 'Al-Hafiz', 'The Preserver', 'حفاظت کرنے والا'),
  AllahName('الْمُقِيتُ', 'Al-Muqit', 'The Sustainer', 'قوت دینے والا'),
  AllahName('الْحَسِيبُ', 'Al-Hasib', 'The Reckoner', 'حسب لینے والا'),
  AllahName('الْجَلِيلُ', 'Al-Jalil', 'The Majestic', 'شان والا'),
  AllahName('الْكَرِيمُ', 'Al-Karim', 'The Generous', 'کرم کرنے والا'),
  AllahName('الرَّقِيبُ', 'Ar-Raqib', 'The Watchful', 'نگرانی کرنے والا'),
  AllahName('الْمُجِيبُ', 'Al-Mujib', 'The Responsive', 'دعا قبول کرنے والا'),
  AllahName('الْوَاسِعُ', 'Al-Wasi', 'The All-Encompassing', 'وسعت والا'),
  AllahName('الْحَكِيمُ', 'Al-Hakim', 'The Wise', 'حکمت والا'),
  AllahName('الْوَدُودُ', 'Al-Wadud', 'The Loving', 'محبت کرنے والا'),
  AllahName('الْمَجِيدُ', 'Al-Majid', 'The Glorious', 'بزرگی والا'),
  AllahName('الْبَاعِثُ', 'Al-Baith', 'The Resurrector', 'دوبارہ اٹھانے والا'),
  AllahName('الشَّهِيدُ', 'Ash-Shahid', 'The Witness', 'گواہ'),
  AllahName('الْحَقُّ', 'Al-Haqq', 'The Truth', 'سچا'),
  AllahName('الْوَكِيلُ', 'Al-Wakil', 'The Trustee', 'کارساز'),
  AllahName('الْقَوِيُّ', 'Al-Qawi', 'The Strong', 'طاقتور'),
  AllahName('الْمَتِينُ', 'Al-Matin', 'The Firm', 'مضبوط'),
  AllahName('الْوَلِيُّ', 'Al-Wali', 'The Protecting Friend', 'دوست و مددگار'),
  AllahName('الْحَمِيدُ', 'Al-Hamid', 'The Praiseworthy', 'قابلِ تعریف'),
  AllahName('الْمُحْصِيُ', 'Al-Muhsi', 'The Enumerator', 'گننے والا'),
  AllahName('الْمُبْدِئُ', 'Al-Mubdi', 'The Initiator', 'شروع کرنے والا'),
  AllahName('الْمُعِيدُ', 'Al-Muid', 'The Restorer', 'لوٹانے والا'),
  AllahName('الْمُحْيِيُ', 'Al-Muhyi', 'The Giver of Life', 'زندگی دینے والا'),
  AllahName('الْمُمِيتُ', 'Al-Mumit', 'The Bringer of Death', 'موت دینے والا'),
  AllahName('الْحَيُّ', 'Al-Hayy', 'The Ever-Living', 'ہمیشہ زندہ'),
  AllahName('الْقَيُّومُ', 'Al-Qayyum', 'The Self-Subsisting', 'سب کو سنبھالنے والا'),
  AllahName('الْوَاجِدُ', 'Al-Wajid', 'The Finder', 'پانے والا'),
  AllahName('الْمَاجِدُ', 'Al-Maajid', 'The Noble', 'مرتبہ والا'),
  AllahName('الْوَاحِدُ', 'Al-Wahid', 'The One', 'ایک'),
  AllahName('الْأَحَدُ', 'Al-Ahad', 'The Unique', 'یکتا'),
  AllahName('الصَّمَدُ', 'As-Samad', 'The Eternal', 'بے نیاز'),
  AllahName('الْقَادِرُ', 'Al-Qadir', 'The Capable', 'قدرت والا'),
  AllahName('الْمُقْتَدِرُ', 'Al-Muqtadir', 'The All-Powerful', 'پوری قدرت والا'),
  AllahName('الْمُقَدِّمُ', 'Al-Muqaddim', 'The Expediter', 'آگے کرنے والا'),
  AllahName('الْمُؤَخِّرُ', 'Al-Muakhkhir', 'The Delayer', 'پیچھے کرنے والا'),
  AllahName('الْأَوَّلُ', 'Al-Awwal', 'The First', 'سب سے پہلا'),
  AllahName('الْآخِرُ', 'Al-Akhir', 'The Last', 'سب سے آخر'),
  AllahName('الظَّاهِرُ', 'Az-Zahir', 'The Manifest', 'ظاہر'),
  AllahName('الْبَاطِنُ', 'Al-Batin', 'The Hidden', 'پوشیدہ'),
  AllahName('الْوَالِي', 'Al-Waali', 'The Governor', 'حاکم'),
  AllahName('الْمُتَعَالِي', 'Al-Mutaali', 'The Most Exalted', 'سب سے برتر'),
  AllahName('الْبَرُّ', 'Al-Barr', 'The Source of Goodness', 'احسان کرنے والا'),
  AllahName('التَّوَّابُ', 'At-Tawwab', 'The Accepter of Repentance', 'توبہ قبول کرنے والا'),
  AllahName('الْمُنْتَقِمُ', 'Al-Muntaqim', 'The Avenger', 'بدلہ لینے والا'),
  AllahName('الْعَفُوُّ', 'Al-Afuww', 'The Pardoner', 'معاف کرنے والا'),
  AllahName('الرَّءُوفُ', 'Ar-Rauf', 'The Most Kind', 'نہایت شفیق'),
  AllahName('مَالِكُ الْمُلْكِ', 'Malik-ul-Mulk', 'The Owner of All', 'سب کا مالک'),
  AllahName('ذُو الْجَلَالِ وَالْإِكْرَامِ', 'Dhul-Jalali wal-Ikram', 'The Lord of Majesty and Generosity', 'جلال و کرم والا'),
  AllahName('الْمُقْسِطُ', 'Al-Muqsit', 'The Equitable', 'انصاف کرنے والا'),
  AllahName('الْجَامِعُ', 'Al-Jami', 'The Gatherer', 'جمع کرنے والا'),
  AllahName('الْغَنِيُّ', 'Al-Ghani', 'The Self-Sufficient', 'بے نیاز'),
  AllahName('الْمُغْنِيُ', 'Al-Mughni', 'The Enricher', 'غنی کرنے والا'),
  AllahName('الْمَانِعُ', 'Al-Mani', 'The Preventer', 'روکنے والا'),
  AllahName('الضَّارَّ', 'Ad-Darr', 'The Distresser', 'ضرر پہنچانے والا'),
  AllahName('النَّافِعُ', 'An-Nafi', 'The Benefactor', 'نفع دینے والا'),
  AllahName('النُّورُ', 'An-Nur', 'The Light', 'نور'),
  AllahName('الْهَادِي', 'Al-Hadi', 'The Guide', 'ہدایت دینے والا'),
  AllahName('الْبَدِيعُ', 'Al-Badi', 'The Incomparable', 'بے مثال'),
  AllahName('الْبَاقِي', 'Al-Baqi', 'The Everlasting', 'ہمیشہ باقی'),
  AllahName('الْوَارِثُ', 'Al-Waris', 'The Inheritor', 'وارث'),
  AllahName('الرَّشِيدُ', 'Ar-Rashid', 'The Guide to the Right Path', 'راہِ راست دکھانے والا'),
  AllahName('الصَّبُورُ', 'As-Sabur', 'The Patient', 'بہت صبر والا'),
];
